using AviationChecklistData.Model;
using Gehtsoft.PDFFlow.Builder;
using Gehtsoft.PDFFlow.Models.Enumerations;
using Gehtsoft.PDFFlow.Models.Shared;
using Gehtsoft.PDFFlow.Utils;
using System.IO;
using System.Globalization;
using Gehtsoft.PDFFlow.UserUtils;

namespace AviationChecklist
{
    internal class AviationChecklistBuilder
    {
        public AviationData AviationData { get; internal set; }

        internal static readonly CultureInfo DocumentLocale
            = new CultureInfo("en-US");
        internal static readonly XUnit PageWidth =
            (PredefinedSizeBuilder.ToSize(PaperSize.Letter).Width -
                (Margins.Left + Margins.Right));
        internal const PageOrientation Orientation
            = PageOrientation.Portrait;
        internal static readonly Box Margins = new Box(29, 21, 29, 12);

        internal static readonly FontBuilder FNT8 = Fonts.Helvetica(8f);
        internal static readonly FontBuilder FNT9 = Fonts.Helvetica(9f);
        internal static readonly FontBuilder FNT9W = Fonts.Helvetica(9f).SetBold().SetColor(Color.White);
        internal static readonly FontBuilder FNT10 = Fonts.Helvetica(10f);
        internal static readonly FontBuilder FNT13 = Fonts.Helvetica(13f);
        internal static readonly FontBuilder FNT11B = Fonts.Helvetica(11f).SetBold();
        internal static readonly FontBuilder FNT19B = Fonts.Helvetica(19f).SetBold();
        internal static readonly FontBuilder FNT24B = Fonts.Helvetica(24f).SetBold();

        internal DocumentBuilder Build()
        {
            DocumentBuilder documentBuilder = DocumentBuilder.New();
            var Section = documentBuilder.AddSection();
            Section.SetOrientation(PageOrientation.Portrait)
                   .SetSize(PaperSize.Letter)
                   .SetMargins(Margins);

            AddHeader(Section);
            AddBody(Section);
            AddFooter(Section);

            return documentBuilder;
        }

        public void AddHeader(SectionBuilder section)
        {
            section.AddHeaderToBothPages(44)
                       .AddTable()
                           .SetBorderStroke(Stroke.None)
                           .SetWidth(XUnit.FromPercent(100))
                           .AddColumnPercentToTable("", 60)
                           .AddColumnPercentToTable("", 40)
                           .AddRow()
                               .AddCell()
                                   .AddParagraph("SamplePlane 123 - For Illustration Purposes")
                                   .SetFont(FNT13)
                               .ToCell()
                                   .AddParagraph("Normal Operating Checklist")
                                   .SetFont(FNT19B)
                           .ToRow()
                               .AddCell()
                                   .SetHorizontalAlignment(HorizontalAlignment.Right)
                                   .AddImage(Path.Combine("images", "AC_Image.png"))
                                       .SetScale(ScalingMode.UserDefined)
                                       .SetWidth(200);
        }
        
        public void AddBody(SectionBuilder section)
        {
            var bodyTable = section.AddTable().SetBorderStroke(Stroke.None);

            bodyTable
                .SetMarginTop(11)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 49)
                .AddColumnPercentToTable("", 2)
                .AddColumnPercentToTable("", 49);

            var row2Builder = bodyTable.AddRow();
            LeftPart(row2Builder.AddCell());
            row2Builder.AddCell();
            RightPart(row2Builder.AddCell());

        }
        public void AddFooter(SectionBuilder section)
        {
            section.AddFooterToBothPages(30)
                   .AddTable()
                       .SetWidth(XUnit.FromPercent(100))
                       .AddColumnPercentToTable("", 33)
                       .AddColumnPercentToTable("", 33)
                       .AddColumnPercentToTable("", 34)
                       .AddRow()
                           .SetBorderWidth(0, 2, 0, 0)
                           .SetFont(FNT8)
                           .AddCellToRow("Version 1.02 March 2021")
                           .AddCell("Copyright © 2021 gsairlines.com")
                               .SetHorizontalAlignment(HorizontalAlignment.Center)
                       .ToRow()
                           .AddCell()
                               .SetHorizontalAlignment(HorizontalAlignment.Right)
                               .AddParagraph()
                                   .AddPageNumberToParagraph("Page ");
        }

        private void PageNumber(TableCellBuilder cellBuilder)
        {
            cellBuilder
                .SetHorizontalAlignment(HorizontalAlignment.Right)
                .AddParagraph("Page ").AddPageNumber();
        }

        private void LeftPart(TableCellBuilder cellBuilder)
        {

            cellBuilder.SetFont(FNT10);
            cellBuilder.AddTable()
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 65)
                .AddColumnPercentToTable("", 35)
                .SetBorderWidth(0, 0, 0, 0.5f)
                .AddRow()
                    .AddCell("SAFETY INSPECTION CHECKLIST", 2, 1)
                        .SetPadding(5, 4, 0, 3).SetFont(FNT9W).SetBackColor(Color.Black).ToTable()
                .AddRow()
                    .AddCell("SURFACES AND CHOCKS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.SurfacesAndChocks)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("MAINTENANCE STATUS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.MaintenanceStatus)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("BATTERY")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.Battery)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("ELECTRIC HYD PUMPS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.ElectricHydPumps)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("SHIPS LIBRARY")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.ShipsLibrary)
                        .SetBold().ToTable();

            cellBuilder.AddTable().SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 65)
                .AddColumnPercentToTable("", 35)
                .SetBorderWidth(0, 0, 0, 0.5f)
                .AddRow()
                    .AddCell("BEFORE TAXI CHECKLIST", 2, 1)
                        .SetPadding(5, 4, 0, 3).SetFont(FNT9W).SetBackColor(Color.Black).ToTable().AddRow()
                    .AddCell("GENERATORS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.Generators)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("PROBE HEAT")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.ProbeHeat)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("ANTI-ICE")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.AntiIce)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("A PUMPS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.APumps)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("AIR CONDITIONING")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.AirConditioning)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("ISOLATION VALVE")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.IsolationValve)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("START SWITCHES")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.StartSwitches)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("APU")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.Apu)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("RECALL")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.Recall)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("FLIGHT CONTROLS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.FlightControlsTaxi)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("FLAPS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.FlapsTaxi)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("STAB TRIM")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.StabTrimTaxi)
                        .SetBold().ToTable()
                .AddRow()
                    .AddCell("START LEVERS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                    .AddCell()
                        .SetPadding(0, 2.5f, 0, 2.5f)
                        .AddParagraph(AviationData.StartLevers)
                        .SetBold().ToTable();

            cellBuilder.AddTable().SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 65)
                .AddColumnPercentToTable("", 35)
                .SetBorderWidth(0, 0, 0, 0.5f)
               .AddRow()
                   .AddCell("BEFORE TAKE OFF CHECKLIST TO THE LINE", 2, 1)
                       .SetPadding(5, 4, 0, 3).SetFont(FNT9W).SetBackColor(Color.Black).ToTable().AddRow()
                   .AddCell("CONFIG")
                       .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                   .AddCell()
                       .SetPadding(0, 2.5f, 0, 2.5f)
                       .AddParagraph(AviationData.Config)
                       .SetBold().ToTable()
               .AddRow()
                   .AddCell("FLAPS")
                       .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                   .AddCell()
                       .SetPadding(0, 2.5f, 0, 2.5f)
                       .AddParagraph(AviationData.FlapsBeforeTakeOff)
                       .SetBold().ToTable()
               .AddRow()
                   .AddCell("STAB TRIM")
                       .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                   .AddCell()
                       .SetPadding(0, 2.5f, 0, 2.5f)
                       .AddParagraph(AviationData.StabBeforeTrimTakeOff)
                       .SetBold().ToTable()
               .AddRow()
                   .AddCell("TAKEOFF BRIEFING")
                       .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                   .AddCell()
                       .SetPadding(0, 2.5f, 0, 2.5f)
                       .AddParagraph(AviationData.TakeoffBriefing)
                       .SetBold().ToTable()
               .AddRow()
                   .AddCell("CABIN")
                       .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                   .AddCell()
                       .SetPadding(0, 2.5f, 0, 2.5f)
                       .AddParagraph(AviationData.Cabin)
                       .SetBold().ToTable();

            cellBuilder.AddTable().SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 65)
                .AddColumnPercentToTable("", 35)
                .SetBorderWidth(0, 0, 0, 0.5f)
              .AddRow()
                  .AddCell("BELOW THE LINE", 2, 1)
                      .SetPadding(5, 4, 0, 3).SetFont(FNT9W).SetBackColor(Color.Black).ToTable().AddRow()
                  .AddCell("MCP (V2, RWY HDG, CLR)")
                      .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Mcp)
                      .SetBold().ToTable()
              .AddRow()
                  .AddCell("TRANSPONDER")
                      .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Transponder)
                      .SetBold().ToTable()
              .AddRow()
                  .AddCell("LANDING LIGHTS")
                      .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.LandingLights)
                      .SetBold().ToTable()
              .AddRow()
                  .AddCell("RETRACTS")
                      .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Retracts)
                      .SetBold().ToTable();
        }

        private void RightPart(TableCellBuilder cellBuilder)
        {
            cellBuilder.SetFont(FNT10);
            cellBuilder.AddTable()
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 65)
                .AddColumnPercentToTable("", 35)
                .SetBorderWidth(0, 0, 0, 0.5f)
                .AddRow()
                    .AddCell("AFTER TAKEOFF CHECKLIST", 2, 1)
                        .SetPadding(5, 4, 0, 3).SetFont(FNT9W).SetBackColor(Color.Black).ToTable().AddRow()
                    .AddCell("AIR CONDITIONING")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.AirConditioningAfterTakeOff)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("AUTOBRAKE")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.AutoBrake)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("START SWITCHES")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.StartSwitchesAfterTakeOff)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("FLAPS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.FlapsAfterTakeOff)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("LANDING GEAR")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.LandingGear)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("ALTIMETERS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Altimeters)
                      .SetBold().ToTable();

            cellBuilder.AddTable().SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 65)
                .AddColumnPercentToTable("", 35)
                .SetBorderWidth(0, 0, 0, 0.5f)
                .AddRow()
                    .AddCell("BEFORE START CHECKLIST TO THE LINE", 2, 1)
                        .SetPadding(5, 4, 0, 3).SetFont(FNT9W).SetBackColor(Color.Black).ToTable().AddRow()
                    .AddCell("PHONES")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Phones)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("IRS MODE SELECTORS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.IrsModeSelectors)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("GEAR PINS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.GearPins)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("LIGHT TEST")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.LightTest)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("OXYGEN")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Oxygen)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("YAW DAMPER")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.YawDamper)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("DISPLAY SWITCHES")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.DisplaySwitches)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("FUEL")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Fuel)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("CABIN / UTIL / IFE")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.CabinUtilIfe)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("EMERGENCY EXIT LIGHTS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.ExitLights)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("PASSENGER SIGNS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.PassSigns)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("WINDOW HEAT")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.WindowHeat)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("HYDRAULICS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Hydraulics)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("AIR COND & PRESS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.AirConditioning)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("PRESSURIZATION MODE")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.PressurizationMode)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("INSTRUMENTS")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Instruments)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("AUTOBRAKE")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Autobrake)
                      .SetBold().ToTable()
                 .AddRow()
                    .AddCell("SPEEDBRAKE LEVER")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.SpeedbraleLevel)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("PARKING BRAKE")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.ParkingBrake)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("STAB TRIM SWITCHES")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.StabBeforeTrimTakeOff)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("WHEEL WELL FIRE WARNING")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.WheelWellFireWarning)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("RADIOS, RADAR & XPONDER")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.RadiosRadarXponder)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("RUDDER & AILERON TRIM")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.PudderAileronTrim)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("TAKEOFF BRIEFING")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.TakeoffBriefing)
                      .SetBold().ToTable()
                .AddRow()
                    .AddCell("PA")
                        .SetPadding(0, 2.5f, 0, 2.5f).ToRow()
                  .AddCell()
                      .SetPadding(0, 2.5f, 0, 2.5f)
                      .AddParagraph(AviationData.Pa)
                      .SetBold().ToTable();

        }
    }

}
