using AviationChecklistData.Model;
using Gehtsoft.PDFFlow.Builder;
using Gehtsoft.PDFFlow.Models.Enumerations;
using Gehtsoft.PDFFlow.Models.Shared;
using Gehtsoft.PDFFlow.Utils;
using System.IO;
using System.Globalization;
using Gehtsoft.PDFFlow.UserUtils;

namespace AviationChecklist
{
    internal class AviationChecklistBuilder
    {
        public AviationData AviationData { get; internal set; }
        public SafetyData SafetyData { get; internal set; }
        public BeforeTaxiData BeforeTaxiData { get; internal set; }
        public BeforeTakeoffData BeforeTakeoffData { get; internal set; }
        public BelowTheLine1Data BelowTheLine1Data { get; internal set; }
        public AfterTakeoffData AfterTakeoffData { get; internal set; }
        public BeforeStartData BeforeStartData { get; internal set; }
        public BelowTheLine2Data BelowTheLine2Data { get; internal set; }
        public DescentData DescentData { get; internal set; }
        public ApproachData ApproachData { get; internal set; }
        public GdFLData GdFLData { get; internal set; }
        public CompleteData CompleteData { get; internal set; }
        public ShutdownData ShutdownData { get; internal set; }
        public SecureData SecureData { get; internal set; }


        internal static readonly CultureInfo DocumentLocale
            = new CultureInfo("en-US");
        internal static readonly XUnit PageWidth =
            (PredefinedSizeBuilder.ToSize(PaperSize.Letter).Width -
                (Margins.Left + Margins.Right));
        internal const PageOrientation Orientation
            = PageOrientation.Portrait;
        internal static readonly Box Margins = new Box(29, 21, 29, 12);

        internal static readonly FontBuilder FNT8 = Fonts.Helvetica(8f);
        internal static readonly FontBuilder FNT9 = Fonts.Helvetica(9f);
        internal static readonly FontBuilder FNT10 = Fonts.Helvetica(10f);
        internal static readonly FontBuilder FNT12 = Fonts.Helvetica(12f);
        internal static readonly FontBuilder FNT13 = Fonts.Helvetica(13f);
        internal static readonly FontBuilder FNT11B = Fonts.Helvetica(11f).SetBold();
        internal static readonly FontBuilder FNT13B = Fonts.Helvetica(13f)
                                                        .SetBold().SetColor(Color.White);
        internal static readonly FontBuilder FNT19B = Fonts.Helvetica(19f).SetBold();
        internal static readonly FontBuilder FNT24B = Fonts.Helvetica(24f).SetBold();

        internal DocumentBuilder Build()
        {
            DocumentBuilder documentBuilder = DocumentBuilder.New();
            var Section = documentBuilder.AddSection();
            Section.SetOrientation(PageOrientation.Portrait)
                   .SetSize(PaperSize.Letter)
                   .SetMargins(Margins);

            AddHeader(Section);
            AddBody1(Section);
            AddFooter(Section);
            AddBody2(Section);

            return documentBuilder;
        }

        public void AddHeader(SectionBuilder section)
        {
            section
                .AddHeaderToBothPages(55)
                    .AddTable()
                    .SetBorderStroke(Stroke.None)
                    .SetWidth(XUnit.FromPercent(100))
                    .AddColumnPercentToTable("", 60)
                    .AddColumnPercentToTable("", 40)
                        .AddRow()
                            .AddCell()
                                .AddParagraph("SamplePlane 123 - For Illustration Purposes")
                                .SetFont(FNT13)
                            .ToCell()
                                .AddParagraph("Normal Operating Checklist")
                                .SetFont(FNT19B)
                        .ToRow()
                            .AddCell()
                            .SetHorizontalAlignment(HorizontalAlignment.Right)
                                .AddImage(Path.Combine("images", "AC_Image.png"))
                                .SetScale(ScalingMode.UserDefined)
                                .SetWidth(200);
        }
        
        public void AddBody1(SectionBuilder section)
        {
            var bodyTable = section.AddTable().SetBorderStroke(Stroke.None);

            bodyTable
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 49)
                .AddColumnPercentToTable("", 2)
                .AddColumnPercentToTable("", 49);

            var row2Builder = bodyTable.AddRow();
            AddLeftPart1(row2Builder.AddCell());
            row2Builder.AddCell();
            AddRightPart1(row2Builder.AddCell());

        }

        public void AddBody2(SectionBuilder section)
        {
            var bodyTable = section.AddTable().SetBorderStroke(Stroke.None);

            bodyTable
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 49)
                .AddColumnPercentToTable("", 2)
                .AddColumnPercentToTable("", 49);

            var row2Builder = bodyTable.AddRow();
            AddLeftPart2(row2Builder.AddCell());
            row2Builder.AddCell();
            AddRightPart2(row2Builder.AddCell());
        }

        public void AddFooter(SectionBuilder section)
        {
            section.AddFooterToBothPages(30)
                   .AddTable()
                       .SetWidth(XUnit.FromPercent(100))
                       .AddColumnPercentToTable("", 33)
                       .AddColumnPercentToTable("", 33)
                       .AddColumnPercentToTable("", 34)
                       .AddRow()
                           .SetBorderWidth(0, 2, 0, 0)
                           .SetFont(FNT8)
                           .AddCellToRow("Version 1.02 March 2021")
                           .AddCell("Copyright © 2021 gsairlines.com")
                               .SetHorizontalAlignment(HorizontalAlignment.Center)
                       .ToRow()
                           .AddCell()
                               .SetHorizontalAlignment(HorizontalAlignment.Right)
                               .AddParagraph()
                                   .AddPageNumberToParagraph("Page ");
        }

        private void AddLeftPart1(TableCellBuilder cellBuilder)
        {

            cellBuilder.SetFont(FNT12);
            cellBuilder
                .AddTable()
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("SAFETY INSPECTION", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.8, 0.01, 0.11))
                .ToTable()
                    .AddRow()
                        .AddCell("SURFACES AND CHOCKS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SafetyData.SurfacesAndChocks)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("MAINTENANCE STATUS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SafetyData.MaintenanceStatus)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("BATTERY")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SafetyData.Battery)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ELECTRIC HYD PUMPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SafetyData.ElectricHydPumps)
                            .SetBold().ToTable()
                    .AddRow()
                        .AddCell("SHIPS LIBRARY")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                            .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SafetyData.ShipsLibrary)
                            .SetBold().ToTable();

            cellBuilder.AddTable().SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("BEFORE TAXI", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.25, 0.46, 0.02))
                .ToTable()
                    .AddRow()
                        .AddCell("GENERATORS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.Generators)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("PROBE HEAT")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.ProbeHeat)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ANTI-ICE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.AntiIce)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("A PUMPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.APumps)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AIR CONDITIONING")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.AirConditioning)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ISOLATION VALVE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.IsolationValve)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("START SWITCHES")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.StartSwitches)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("APU")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.Apu)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("RECALL")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.Recall)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("FLIGHT CONTROLS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.FlightControls)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("FLAPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.Flaps)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("STAB TRIM")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.StabTrim)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("START LEVERS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTaxiData.StartLevers)
                            .SetBold();

            cellBuilder
                .AddTable()
                .SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("BEFORE TAKE OFF TO THE LINE", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.25, 0.46, 0.02))
                .ToTable()
                    .AddRow()
                        .AddCell("CONFIG")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTakeoffData.Config)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("FLAPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTakeoffData.Flaps)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("STAB TRIM")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTakeoffData.StabTrim)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("TAKEOFF BRIEFING")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTakeoffData.TakeoffBriefing)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("CABIN")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeTakeoffData.Cabin)
                            .SetBold();

            cellBuilder
                .AddTable()
                .SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("BELOW THE LINE", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.25, 0.46, 0.02))
                .ToTable()
                    .AddRow()
                        .AddCell("MCP (V2, RWY HDG, CLR)")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine1Data.Mcp)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("TRANSPONDER")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine1Data.Transponder)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("LANDING LIGHTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine1Data.LandingLights)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("RETRACTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine1Data.Retracts)
                            .SetBold();
        }

        private void AddRightPart1(TableCellBuilder cellBuilder)
        {
            cellBuilder.SetFont(FNT12);
            cellBuilder
                .AddTable()
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("AFTER TAKEOFF", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.25, 0.46, 0.02))
                .ToTable()
                    .AddRow()
                        .AddCell("AIR CONDITIONING")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(AfterTakeoffData.AirConditioning)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AUTOBRAKE")
                            .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                            .SetPadding(0, 2, 0, 0)
                            .AddParagraph(AfterTakeoffData.AutoBrake)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("START SWITCHES")
                        .SetPadding(0, 2, 0, 0).ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(AfterTakeoffData.StartSwitches)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("FLAPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(AfterTakeoffData.Flaps)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("LANDING GEAR")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(AfterTakeoffData.LandingGear)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ALTIMETERS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                            .SetPadding(0, 2, 0, 0)
                            .AddParagraph(AfterTakeoffData.Altimeters)
                            .SetBold();

            cellBuilder
                .AddTable()
                .SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("BEFORE START TO THE LINE", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.25, 0.46, 0.02))
                .ToTable()
                    .AddRow()
                        .AddCell("PHONES")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.Phones)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("IRS MODE SELECTORS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.IrsModeSelectors)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("GEAR PINS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.GearPins)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("LIGHT TEST")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.LightTest)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("OXYGEN")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.Oxygen)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("YAW DAMPER")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.YawDamper)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("DISPLAY SWITCHES")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.DisplaySwitches)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("FUEL")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.Fuel)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("CABIN / UTIL / IFE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.CabinUtilIfe)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("EMERGENCY EXIT LIGHTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.ExitLights)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("PASSENGER SIGNS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.PassSigns)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("WINDOW HEAT")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.WindowHeat)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("HYDRAULICS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.Hydraulics)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AIR COND & PRESS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.ACP)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("PRESSURIZATION MODE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.PressurizationMode)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("INSTRUMENTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.Instruments)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AUTOBRAKE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.Autobrake)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("SPEEDBRAKE LEVER")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.SpeedbraleLevel)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("PARKING BRAKE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.ParkingBrake)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("STAB TRIM SWITCHES")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.StabTrimSwitches)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("WHEEL WELL FIRE WARNING")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.WheelWellFireWarning)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("RADIOS, RADAR & XPONDER")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.RadiosRadarXponder)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("RUDDER & AILERON TRIM")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.PudderAileronTrim)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("TAKEOFF BRIEFING")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.TakeoffBriefing)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("PA")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BeforeStartData.Pa)
                            .SetBold();
        }

        private void AddLeftPart2(TableCellBuilder cellBuilder)
        {

            cellBuilder.SetFont(FNT12);
            cellBuilder
                .AddTable()
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("BELOW THE LINE", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.29, 0.57, 0.88))
                .ToTable()
                    .AddRow()
                        .AddCell("A PUMPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine2Data.APumps)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AIR CONDITIONING PACKS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine2Data.AirConditioningPacks)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ANTI COLLISION LIGHTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine2Data.AntiCollisionLights)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("PARKING BRAKE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine2Data.ParkingBrake)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("TRANSPONDER")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(BelowTheLine2Data.Transponder)
                            .SetBold()
                            .ToTable();

            cellBuilder
                .AddTable()
                .SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("DESCENT", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.29, 0.57, 0.88))
                .ToTable()
                    .AddRow()
                        .AddCell("PRESSUARIZATION")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(DescentData.Pressurization)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ANTI ICE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(DescentData.AntiIce)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("APPROACH BRIEF AND FUEL")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(DescentData.ApproachBriefAndFuel)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("IAS AND ALT BUGS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(DescentData.IasAndAltBugs)
                            .SetBold();

            cellBuilder
                .AddTable()
                .SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("APPROACH", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.29, 0.57, 0.88))
                .ToTable()
                    .AddRow()
                        .AddCell("ALTIMETERS AND INSTRUMENTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ApproachData.AltimetersAndInstruments)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("APPROACH AIDS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ApproachData.ApproachAids)
                            .SetBold();

            cellBuilder
                .AddTable()
                .SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("GEAR DOWN, FLAPS, LANDING", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.29, 0.57, 0.88))
                .ToTable()
                    .AddRow()
                        .AddCell("ENGINE START SWITCHES")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(GdFLData.EngineStartSwitches)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("RECALL")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(GdFLData.Recall)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("SPEEDBRAKE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(GdFLData.Speedbrake)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("LANDING GEAR")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(GdFLData.LandingGear)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AUTOBRAKE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(GdFLData.Autobrake)
                            .SetBold();

            cellBuilder
                .AddTable().SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("COMPLETE", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.96, 0.65, 0.14))
                .ToTable()
                    .AddRow()
                        .AddCell("FLAPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(CompleteData.Flaps)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("LANDING LIGHTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(CompleteData.LandingLights)
                            .SetBold();
        }

        private void AddRightPart2(TableCellBuilder cellBuilder)
        {
            cellBuilder.SetFont(FNT12);
            cellBuilder
                .AddTable()
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("SHUTDOWN", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.96, 0.65, 0.14))
                .ToTable()
                    .AddRow()
                        .AddCell("FUEL")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.Fuel)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ELECTRICAL (APU, GPU)")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.ElectricalApuGpu)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("FASTEN BELTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.FastenBelts)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("WINDOW HEAT")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.WindowHeat)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("PROBE HEAT")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.ProbeHeat)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ANTI ICE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.AntiIce)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("ELECTRIC HYD PUMPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.ElectricHydPumps)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("VOICE RECORDER")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.VoiceRecorder)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AIR CONDITIONING")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.AirConditioning)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("EXTERIOR LIGHTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.ExteriorLights)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("START SWITCHES")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.StartSwitches)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AUTOBRAKE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.Autobrake)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("SPEEDBRAKE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.Speedbrake)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("FLAPS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.Flaps)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("PARKING BRAKE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.ParkingBrake)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("START LEVERS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.StartLevers)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("WEATHER RADAR")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.WeatherRadar)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("TRANSPONDER")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.Transponder)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("CVR CB")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.CvrCb)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("COCKPIT DOOR")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(ShutdownData.CockpitDoor)
                            .SetBold();

            cellBuilder
                .AddTable()
                .SetMarginTop(10)
                .SetWidth(XUnit.FromPercent(100))
                .AddColumnPercentToTable("", 68)
                .AddColumnPercentToTable("", 32)
                .SetBorderWidth(0, 0, 0, 0.5f)
                    .AddRow()
                        .AddCell("SECURE", 2, 1)
                        .SetPadding(6, 2, 0, 0).SetFont(FNT13B)
                        .SetBackColor(Color.FromRgba(0.8, 0.01, 0.11))
                .ToTable()
                    .AddRow()
                        .AddCell("IRS MODE SELECTORS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SecureData.IrsModeSelectors)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("CAB / UTIL, IFE")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SecureData.CabUtilIfe)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("AIR CONDITIONING PACKS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SecureData.AirConditioningPacks)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("EMERGENCY EXIT LIGHTS")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SecureData.EmergencyExitLights)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("APU / GPU")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SecureData.ApuGpu)
                            .SetBold()
                .ToTable()
                    .AddRow()
                        .AddCell("BATTERY")
                        .SetPadding(0, 2, 0, 0)
                    .ToRow()
                        .AddCell()
                        .SetPadding(0, 2, 0, 0)
                            .AddParagraph(SecureData.Battery)
                            .SetBold();

        }
    }
}
